const express =  require ('express')
const router = express.Router();
// const mongoose = require ('mongoose');
const GhemassagesController = require('../controllers/site/ghemassage');
const Ghemassage = require("../models/ghemassage");
var Cart = require('../models/cart');
 var bodyParser = require('body-parser');
 var urlencodedParser = bodyParser.urlencoded({ extended: false })
// mongoose.connect('mongodb://localhost/ghemassage',{useMongoClient:true});
// mongoose.Promise = global.Promise;
router.post('/',GhemassagesController.ghemassages_get_search);
router.get('/',GhemassagesController.ghemassages_get_home);
router.get('/san-pham-giam-gia-flash-sale',GhemassagesController.ghemassages_get_flashsale);
router.post('/ghe-massage-ban-chay-nhat',GhemassagesController.ghemassages_bestsell_sort);
router.get('/ghe-massage-ban-chay-nhat',GhemassagesController.ghemassages_get_bestsell);
router.get('/ghe-massage-boss',GhemassagesController.ghemassages_get_trademark_boss);
router.get('/ghe-massage-okia',GhemassagesController.ghemassages_get_trademark_okia);
router.get('/ghe-massage-poogsan',GhemassagesController.ghemassages_get_trademark_poogsan);
router.get('/ghe-massage-maxcare',GhemassagesController.ghemassages_get_trademark_maxcare);
router.get('/ghe-massage-osim',GhemassagesController.ghemassages_get_trademark_osim);
router.get('/ghe-massage-inada',GhemassagesController.ghemassages_get_trademark_inada);
router.get('/ghe-massage-drcare',GhemassagesController.ghemassages_get_trademark_drcare);
router.get('/ghe-massage-panasonic',GhemassagesController.ghemassages_get_trademark_panasonic);
router.post('/may-chay-bo-ban-chay-nhat',GhemassagesController.maychaybo_bestsell_sort);
router.get('/may-chay-bo-ban-chay-nhat',GhemassagesController.maychaybo_get_bestsell);
router.get('/may-chay-bo-yuki',GhemassagesController.maychaybo_get_trademark_yuki);
router.get('/may-chay-bo-like',GhemassagesController.maychaybo_get_trademark_like);
router.get('/may-chay-bo-takasha',GhemassagesController.maychaybo_get_trademark_takasha);
router.get('/may-chay-bo-max',GhemassagesController.maychaybo_get_trademark_max);
router.get('/may-chay-bo-goodforsalas',GhemassagesController.maychaybo_get_trademark_goodforsalas);
router.get('/may-chay-bo-xapon',GhemassagesController.maychaybo_get_trademark_xapon);
router.get('/may-chay-bo-gym',GhemassagesController.maychaybo_get_trademark_gym);
router.get('/may-chay-bo-kingport',GhemassagesController.maychaybo_get_trademark_kingport);
router.get('/bep-tu-bep-hong-ngoai-ban-chay-nhat',GhemassagesController.bep_get_bestsell);
router.get('/ghe-massage/:ghemassagenameseo',GhemassagesController.ghemassages_get_ghemassagenameseo);
router.get('/may-chay-bo/:ghemassagenameseo',GhemassagesController.ghemassages_get_ghemassagenameseo_maychaybo);
router.get('/bep-tu-bep-hong-ngoai/:ghemassagenameseo',GhemassagesController.ghemassages_get_ghemassagenameseo_bep);
router.get('/san-pham-giam-gia-flash-sale/:ghemassagenameseo',GhemassagesController.ghemassages_get_ghemassagenameseo_sanpham_flashsale);
router.get('/tim-kiem/:id',GhemassagesController.ghemassages_get_ghemassageKeyword);
router.get('/tim-kiem-san-pham/:ghemassagenameseo',GhemassagesController.ghemassages_get_ghemassage_timkiemsanpham);
module.exports = router;
